/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package primefactorkotlin

class PrimeFactor {
    companion object {
        fun calculate(number: Int): List<Int> {
            if (number == 1) {
                return emptyList()
            }

            var mutableNumber = number
            val result = emptyList<Int>().toMutableList()

            for (primeFactor in 2..3) {
                while (mutableNumber > 1 && mutableNumber % primeFactor == 0) {
                    result.add(primeFactor)
                    mutableNumber /= primeFactor
                }
            }

            return result
        }
    }
}
