/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package primefactorkotlin

class PrimeFactor {
    companion object {
        fun calculate(number: Int): List<Int> {
            if (number == 1) {
                return emptyList()
            }

            var mutableNumber = number
            val primeFactors = emptyList<Int>().toMutableList()

            for (currentFactor in 2..3) {
                while (mutableNumber % currentFactor == 0) {
                    primeFactors.add(currentFactor)
                    mutableNumber /= currentFactor
                }
            }

            return primeFactors
        }
    }
}
