/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package primefactorkotlin

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertTrue

class PrimeFactorTest {
    @Test
    fun `Prime factor of one in none`() {
        val sui = 1

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(emptyList(), primeFactors)
    }

    @Test
    fun `Prime factor of two is two`() {
        val sui = 2

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(2), primeFactors)
    }

    @Test
    fun `Prime factor of three is three`() {
        val sui = 3

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(3), primeFactors)
    }

    @Test
    fun `Prime factor of four is listOf(2, 2)`() {
        val sui = 4

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(2, 2), primeFactors)
    }

    @Test
    fun `Prime factor of six is listOf(2, 3)`() {
        val sui = 6

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(2, 3), primeFactors)
    }

    @Test
    fun `Prime factor of eight is listOf(2, 2, 2)`() {
        val sui = 8

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(2, 2, 2), primeFactors)
    }

    @Test
    fun `Prime factor of nine is listOf(3, 3)`() {
        val sui = 9

        val primeFactors = PrimeFactor.calculate(sui)

        assertContentEquals(listOf(3, 3), primeFactors)
    }
}
