/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wrapstringkotlin

class Wrapper {
    companion object {
        fun wrap(string: String, bounds: Int): Array<String> {
            if (string.length <= bounds) {
                return arrayOf(string)
            }

            val spaceIndex = string.indexOfFirst { it == ' '}
            val wrapIndex: Int
            val offset: Int

            if (spaceIndex > -1) {
                wrapIndex = spaceIndex
                offset = 1
            } else {
                wrapIndex = bounds
                offset = 0
            }

            val firstPart = string.substring(0, wrapIndex)
            val secondPart = string.substring(wrapIndex + offset)

            return arrayOf(firstPart) + wrap(secondPart, bounds)
        }
    }
}
